In [1]:
#NumPy - Numerical Python

In [2]:
import numpy as np

In [3]:
#Array

In [4]:
a = np.array([1,2,43])

In [5]:
a


array([ 1,  2, 43])

In [6]:
type(a)

numpy.ndarray

In [7]:
print(a.shape)

(3,)


In [16]:
b= np.array([[1,2,3],[4,56,778]])

In [17]:
type(b)

numpy.ndarray

In [18]:
b

array([[  1,   2,   3],
       [  4,  56, 778]])

In [10]:
b.shape

(2, 3)

In [14]:
c= np.array([[[1,2,3],[4,56,778]]])

In [15]:
c

array([[[  1,   2,   3],
        [  4,  56, 778]]])

In [19]:
c.shape

(1, 2, 3)

In [20]:
d= np.array([[[[1,2,3],[4,56,778]]]])

In [21]:
d

array([[[[  1,   2,   3],
         [  4,  56, 778]]]])

In [22]:
d.shape

(1, 1, 2, 3)

In [23]:
a=np.zeros((2,2))

In [24]:
a

array([[ 0.,  0.],
       [ 0.,  0.]])

In [25]:
np.ones((2,2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [26]:
#Array index

In [40]:
b= np.array([[1,2,3],[4,56,778]])

In [41]:
b

array([[  1,   2,   3],
       [  4,  56, 778]])

In [42]:
b.shape

(2, 3)

In [48]:
b[:, 0:2]

array([[ 1,  2],
       [ 4, 56]])

In [49]:
b[:, :]

array([[  1,   2,   3],
       [  4,  56, 778]])

In [54]:
b[:, :3]

array([[  1,   2,   3],
       [  4,  56, 778]])

In [57]:
b[:1, 0:2]

array([[1, 2]])

In [58]:
a = np.array([[1,2,3], [3,4,5], [4,5,6]])

In [59]:
a.shape

(3, 3)

In [60]:
a[1, :]

array([3, 4, 5])

In [61]:
a[1:2, :]

array([[3, 4, 5]])

In [62]:
print(a.shape)

(3, 3)


In [63]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [64]:
rule = (a>10)

In [65]:
print(rule)

[[False False False]
 [False False False]
 [False False False]]


In [66]:
a[rule]

array([], dtype=int32)

In [69]:
rule = (a<2)

In [70]:
rule

array([[ True, False, False],
       [False, False, False],
       [False, False, False]], dtype=bool)

In [71]:
np.int64

numpy.int64

In [72]:
np.float64

numpy.float64

In [73]:
np.float32

numpy.float32

In [74]:
np.object

object

In [76]:
np.complex

complex

In [77]:
np.string_

numpy.bytes_

In [78]:
np.unicode_

numpy.str_

In [79]:
a = np.array([1,23])

In [81]:
b = np.array([[1,5,6,7], [5,46,6]])
print(b)

[[1, 5, 6, 7] [5, 46, 6]]


In [86]:
b = np.array([(1,5,6,7), (5,46,6)], dtype=float)
print(b)

ValueError: setting an array element with a sequence.

In [87]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [88]:
a = np.ones((2,3,4))

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [89]:
len(a)

2

In [90]:
a.shape


(2,)

In [91]:
a = np.array([1,23])
b = np.array([[1,5,6,7], [5,46,6]])

print(a == b) 

[False False]
